api/urls.py
from django.urls import path, include

app_name = 'api'
urlpatterns = [
    path('users/', include('api.users.urls', namespace='user')),
    path('schedules/', include('api.schedules.urls', namespace='schedule')),
    path('celebrities/', include('api.celebritys.urls', namespace='celebrity')),
    path('devices/', include('api.devices.urls', namespace='device')),
    path('feedbacks/', include('api.feedbacks.urls', namespace='feedback')),
    path('notifications/', include('api.notifications.urls', namespace='notification')),
]

api/users/urls.py
from django.urls import path
from .views import (
    UserSocialLoginView, UserLoginView, UserModelViewSet,
    UserInfoView, UserImageView, UserSignupAPIView,
)

app_name = 'user'
urlpatterns = [
    path('', UserSignupAPIView.as_view()),
    path('info/', UserInfoView.as_view(), name='info'),
    path('image', UserImageView.as_view(), name='image'),
    path('social', UserSocialLoginView.as_view(), name='social'),
    path('login', UserLoginView.as_view(), name='login'),
    path('<str:uuid>/', UserModelViewSet.as_view({
        'get': 'retrieve'
    })),
]

apps/users/urls.py
from django.urls import path

from .views import (
    UserFanListView,
    UserFanAPIView,
    UserManagerListView,
    UserManagerCreateView,
    UserLoginView,
    UserLogoutView,
)

app_name = 'user'
urlpatterns = [
    path('login', UserLoginView.as_view(), name='login'),
    path('logout', UserLogoutView.as_view(), name='logout'),
    path('fan', UserFanListView.as_view(), name='fan'),
    path('fan/<int:pk>', UserFanAPIView.as_view(), name='fan_detail'),
    path('manager', UserManagerListView.as_view(), name='manager'),
    path('manager/create', UserManagerCreateView.as_view(), name='manager_create'),
]

apps/users/models.py
import uuid
import json

from django.db import models
from django.conf import settings
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class MyUserQuerySet(models.QuerySet):
    def user(self):
        return self.filter(is_manager=False, is_admin=False)

    def manager(self):
        return self.filter(is_manager=True, is_admin=False)

    def admin(self):
        return self.filter(is_manager=True, is_admin=True)


class MyUserManager(BaseUserManager):
    def get_queryset(self):
        return MyUserQuerySet(self.model, using=self._db)

    def _create_user(self, email, password, **kwargs):
        user = self.model(
            email=self.normalize_email(email),
            **kwargs
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **kwargs):
        return self._create_user(email, password, **kwargs)

    def create_manager(self, email, password, **kwargs):
        kwargs.setdefault('is_manager', True)
        return self._create_user(email, password, **kwargs)

    def create_superuser(self, email, password, **kwargs):
        kwargs.setdefault('is_admin', True)
        return self._create_user(email, password, **kwargs)

    def user(self):
        return self.get_queryset().user()

    def manager(self):
        return self.get_queryset().manager()

    def admin(self):
        return self.get_queryset().admin()


def user_profile_image(instance, filename):
    return "%s/%s" % (instance.uuid, filename)


class MyUser(AbstractBaseUser):
    # 유저 모델
    SEX = (
        ('f', '여자'),
        ('m', '남자'),
    )
    PROVIDER = (
        ('celuv', '셀럽'),
        ('facebook', '페이스북'),
        ('kakao', '카카오'),
        ('google', '구글'),
    )

    uuid = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
        auto_created=True,
        unique=True,
        verbose_name="pk"
    )
    email = models.EmailField(
        unique=True,
        verbose_name='이메일'
    )
    provider = models.CharField(
        max_length=10,
        choices=PROVIDER,
        default='c',
        verbose_name='가입경로'
    )
    uid = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name='소셜로그인 키',
        help_text='소셜로그인인 경우만'
    )
    name = models.CharField(
        max_length=20,
        null=True,
        blank=True,
        verbose_name='이름'
    )
    image = models.ImageField(
        upload_to=user_profile_image,
        null=True,
        blank=True,
        verbose_name='프로필 이미지'
    )
    sex = models.CharField(
        max_length=1,
        choices=SEX,
        null=True,
        blank=True,
        verbose_name='성별'
    )
    birth = models.DateField(
        null=True,
        blank=True,
        verbose_name='생일'
    )
    phone = models.CharField(
        max_length=14,
        null=True,
        blank=True,
        verbose_name='연락처'
    )

    date_joined = models.DateTimeField(
        auto_now_add=True,
        verbose_name='가입일'
    )

    is_active = models.BooleanField(
        default=True,
        verbose_name='활성화 여부'
    )
    is_manager = models.BooleanField(
        default=False,
        verbose_name='매니저 여부'
    )
    is_admin = models.BooleanField(
        default=False,
        verbose_name='관리자 여부'
    )

    objects = MyUserManager()

    USERNAME_FIELD = 'email'

    class Meta:
        db_table = 'user'
        verbose_name = '유저'
        verbose_name_plural = '유저들'

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    @property
    def get_profile_image(self):
        if not self.image:
            return None
        return self.image.url

    @property
    def get_report_count(self):
        return 0

    @property
    def get_feedback_count(self):
        return 0

    @property
    def get_celeb_count(self):
        return 0

apps/users/forms.py
from django import forms
from django.forms import inlineformset_factory
from django_select2 import forms as select2_forms

from .models import MyUser
from apps.celebritys.models import Celebrity
from apps.entertainments.models import Manager


class UserFanForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = [
            'email',
            'phone'
        ]


class UserManagerForm(forms.ModelForm):
    password = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput({
            'placeholder': '비밀번호'
        })
    )
    password1 = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput({
            'placeholder': '비밀번호 확인'
        })
    )

    class Meta:
        model = MyUser
        fields = [
            'email',
            'password',
            'password1',
            'name',
            'phone',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            if field:
                if type(field.widget) in (forms.TextInput, forms.EmailInput):
                    field.widget = forms.TextInput(
                        attrs={'placeholder': field.label})

    def clean(self):
        if self.cleaned_data['password'] != self.cleaned_data['password1']:
            raise forms.ValidationError('비밀번호을 다시 확인해주세요.')

    def save(self, commit=True):
        user = super().save(commit)
        user.is_manager = True
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class ManagerForm(forms.ModelForm):
    celebrity = forms.ModelMultipleChoiceField(
        label="담당 셀럽",
        queryset=Celebrity.objects.all(),
        widget=select2_forms.Select2MultipleWidget,
        required=False,
    )

    class Meta:
        model = Manager
        fields = [
            'entertainment',
            'manager_type',
            'position',
            'celebrity',
        ]


ManagerFormSet = inlineformset_factory(
    MyUser, Manager, form=ManagerForm, extra=1, can_delete=False)

api/users/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.generics import GenericAPIView, RetrieveUpdateAPIView, UpdateAPIView
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from rest_framework_jwt.settings import api_settings

from .serializers import (
    UserSocialSerializer, UserSerializer, UserInfoSerializer,
    UserImageSerializer, UserFindPasswordSerializer,
    UserSignupSerializer,
)

from rest_framework_jwt.views import ObtainJSONWebToken, jwt_response_payload_handler


class UserSocialLoginView(GenericAPIView):
    # 소셜 로그인 API
    permission_classes = [AllowAny]
    serializer_class = UserSocialSerializer

    def create_token(self, user):
        # 비밀번호가 없는 소셜 유저에 대한 인증 토큰 발급
        jwt_payload_handler = api_settings.JWT_PAYLOAD_HANDLER
        jwt_encode_hanlder = api_settings.JWT_ENCODE_HANDLER
        payload = jwt_payload_handler(user)
        token = jwt_encode_hanlder(payload)
        return token

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        user = serializer.save()
        token = self.create_token(user)
        response_data = jwt_response_payload_handler(token, user, request)
        response = Response(response_data)

        return response


class UserLoginView(ObtainJSONWebToken):
    permission_classes = [AllowAny]

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            user = serializer.object.get('user') or request.user
            token = serializer.object.get('token')
            response_data = jwt_response_payload_handler(token, user, request)
            response = Response(response_data)

            return response

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class UserModelViewSet(ModelViewSet):
    permission_classes = [AllowAny]
    serializer_class = UserSerializer
    queryset = get_user_model().objects.all()
    lookup_field = 'uuid'


class UserSignupAPIView(GenericAPIView):
    permission_classes = [AllowAny]
    serializer_class = UserSignupSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        get_user_model().objects.create_user(
            email=serializer.data.get('email'),
            password=serializer.data.get('password')
        )
        return Response()


class UserInfoView(UpdateAPIView):
    serializer_class = UserInfoSerializer

    def get_object(self):
        return self.request.user

    def post(self, request, *args, **kwargs):
        return self.partial_update(request, *args, **kwargs)


class UserImageView(UpdateAPIView):
    serializer_class = UserImageSerializer

    def get_object(self):
        return self.request.user

    def post(self, request, *args, **kwargs):
        return self.partial_update(request, *args, **kwargs)


class UserFindPasswordAPIView(GenericAPIView):
    permission_classes = [AllowAny]
    serializer_class = UserFindPasswordSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        email = serializer.data.get('email')
        return Response()

apps/users/views.py
from django.views.generic import (
    ListView, CreateView, UpdateView,
    View
)
from django.urls import reverse_lazy
from django.db import transaction
from django.contrib.auth.views import LoginView, LogoutView
from rest_framework.generics import RetrieveUpdateAPIView, CreateAPIView

from .models import MyUser
from .forms import UserManagerForm, UserFanForm, ManagerFormSet
from .serializers import MyUserFanSerializer, MyUserManagerSerializer


class UserLoginView(LoginView):
    template_name = 'user/login.html'
    success_url = reverse_lazy('base:home')


class UserLogoutView(LogoutView):
    pass


class UserFanListView(ListView):
    template_name = 'user/fan_list.html'
    queryset = MyUser.objects.user()


class UserFanUpdateView(UpdateView):
    template_name = 'user/fan_update.html'
    queryset = MyUser.objects.user()
    form_class = UserFanForm
    success_url = reverse_lazy('user:fan')


class UserFanAPIView(RetrieveUpdateAPIView):
    serializer_class = MyUserFanSerializer
    queryset = MyUser.objects.user()


class UserManagerListView(ListView):
    template_name = 'user/manager_list.html'
    queryset = MyUser.objects.manager()


class UserManagerCreateView(CreateView):
    # 소속사 매니저 생성 페이지
    template_name = 'user/manager_create.html'
    model = MyUser
    form_class = UserManagerForm
    success_url = reverse_lazy('user:manager')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            formset = ManagerFormSet(self.request.POST)
        else:
            formset = ManagerFormSet()
        context.update({
            'formset': formset
        })
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        manager = context['formset']
        with transaction.atomic():
            self.object = form.save()
            if manager.is_valid():
                manager.instance = self.object
                manager.save()
        return super().form_valid(form)

apps/users/templates/user/admin_list.html
{% extends 'base.html' %}

{% block javascript %}
<script>
    $(function() {
        $('#createManager').ajaxForm({
            success: function(res) {
                location.reload();
            }
        })
    })
</script>
{% endblock %}

{% block content %}
<div class="container main user">
    <h2 class="title">소속사 매니저</h2>
    <h4 class="sub-title">
        <a href="{% url 'user:fan' %}">팬 계정</a>
    </h4>
    <div class="search-area">
        <input type="search" placeholder="검색어를 입력하세요" name='search' />
    </div>
    <div class="user-list">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">NO</th>
                    <th scope="col">권한</th>
                    <th scope="col">아이디</th>
                    <th scope="col">이메일</th>
                    <th scope="col">관리자명</th>
                    <th scope="col">마지막 접속 일시</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <td>{{ object.pk }}</td>
                    <td>{{ object }}</td>
                    <td>{{ object.username }}</td>
                    <td>{{ object.email }}</td>
                    <td>{{ object.name }}</td>
                    <td>{{ object.last_login|date:"Y/m/d h:m" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="">
        <button class="btn" data-toggle="modal" data-target="#createManagerModal">소속사 관리자 추가</button>
    </div>
</div>
{% endblock %}

{% block modal %}
<div class="modal fade" id="createManagerModal" tabindex="-1" role="dialog" aria-labelledby="createManagerModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form method="POST" action="{% url 'user:manager_create' %}" id="createManager">
            {% csrf_token %}
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">관리자 신규 정보</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                    {% for field in form %}
                        <div class="form-group row">
                            <label for="{{ field.id }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                            <div class="input col-sm-10">
                            {{ field }}
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn" data-dismiss="modal">취소</button>
                    <button type="submit" class="btn">등록</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

apps/users/templates/user/fan_list.html
{% extends 'base.html' %}

{% block javascript %}
<script>
$(function() {
  $('#updateUserModal').on('show.bs.modal', function (e) {
    var user_id = $(e.relatedTarget).data('id');
    var modal = $(this);
    $.ajax({
      url: '{% url "user:fan" %}/' + user_id,
      method: 'GET',
      success: function(res) {
        $.each(res, function( key, value) {
          modal.find('input[name=' + key + ']').val(value);
        })
      }
    })
  })
  $('#updateUserModal').on('hide.bs.modal', function (e) {
    var modal = $(this);
    modal.find('input').each(function() {
      $(this).val('');
    })
  })
});

function deactiveUser(e, user_id, is_active) {
  if (user_id === null) {
    var user_id = $(e).parent().parent().find('input[name=pk]').val();
    var is_active = true;
  }
  $.ajax({
    url: '{% url "user:fan" %}/' + user_id,
    method: 'PATCH',
    data: {
      "is_active": !is_active,
    },
    success: function(res) {
      location.reload();
    }
  })
}
</script>
{% endblock %}

{% block content %}
<div class="container main user">
    <h2 class="title">팬 계정</h2>
    <h4 class="sub-title">
      <a href="{% url 'user:manager' %}">소속사 매니저</a>
    </h4>
    <div class="search-area">
      <input type="search" placeholder="검색어를 입력하세요" name='search' />
    </div>
    <div class="user-list">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">NO</th>
            <th scope="col">상태</th>
            <th scope="col">사진</th>
            <th scope="col">사용자 ID</th>
            <th scope="col">가입 채널</th>
            <th scope="col">닉네임</th>
            <th scope="col">가입일</th>
            <th scope="col">성별</th>
            <th scope="col">제보</th>
            <th scope="col">피드백</th>
            <th scope="col">관심 샐럽</th>
            <th scope="col">관리</th>
          </tr>
        </thead>
          <tbody>
            {% for object in object_list %}
              <tr>
                <td data-toggle="modal" data-target="#updateUserModal" data-id="{{ object.pk }}">{{ object.pk }}</td>
                <td data-toggle="modal" data-target="#updateUserModal" data-id="{{ object.pk }}">
                  {% if object.is_active %}
                    정상
                  {% else %}
                    차단
                  {% endif %}
                </td>
                <td data-toggle="modal" data-target="#updateUserModal" data-id="{{ object.pk }}">
                  {% if object.get_profile_iamge %}
                    <img src="{{ object.get_profile_image }}" />
                  {% else %}
                    <div class="empty-image" />
                  {% endif %}
                </td data-toggle="modal" data-target="#updateUserModal" data-id="{{ object.pk }}">
                <td data-toggle="modal" data-target="#updateUserModal" data-id="{{ object.pk }}">{{ object.username }}</td>
                <td data-toggle="modal" data-target="#updateUserModal" data-id="{{ object.pk }}">{{ object.get_provider_display }}</td>
                <td data-toggle="modal" data-target="#updateUserModal" data-id="{{ object.pk }}">
                  {% if object.name %}
                    {{ object.name }}
                  {% else %}
                    -
                  {% endif %}
                </td>
                <td data-toggle="modal" data-target="#updateUserModal" data-id="{{ object.pk }}">{{ object.date_joined|date:"Y/m/d h:m" }}</td>
                <td data-toggle="modal" data-target="#updateUserModal" data-id="{{ object.pk }}">
                  {% if object.sex %}
                    {{ object.get_sex_display }}
                  {% else %}
                    -
                  {% endif %}
                </td>
                <td data-toggle="modal" data-target="#updateUserModal" data-id="{{ object.pk }}">{{ object.get_report_count }}</td>
                <td data-toggle="modal" data-target="#updateUserModal" data-id="{{ object.pk }}">{{ object.get_feedback_count }}</td>
                <td data-toggle="modal" data-target="#updateUserModal" data-id="{{ object.pk }}">{{ object.get_celeb_count }}</td>
                <td style="cursor: pointer;" onclick="deactiveUser(this, {{ object.pk}}, {% if object.is_active %}true{% else %}false{% endif %})">
                  {% if object.is_active %}
                    차단
                  {% else %}
                    차단 해제
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
      </table>
    </div>
</div>
{% endblock %}

{% block modal %}
<div class="modal fade" id="updateUserModal" tabindex="-1" role="dialog" aria-labelledby="updateUserModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">사용자 정보</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <img class="profile" src="" />
          <h4 class="sub-title">기본정보</h4>
          <input type="hidden"disabled class="form-control" id="id_pk" name='pk'>
          <div class="form-group">
            <label for="id_username" class="col-form-label">사용자 ID</label>
            <input type="text" disabled class="form-control" id="id_username" name='username'>
          </div>
          <div class="form-group">
            <label for="id_email" class="col-form-label">이메일</label>
            <input type="text" disabled class="form-control" id="id_email" name='email'>
          </div>
          <div class="form-group">
            <label for="id_provider" class="col-form-label">가입채널</label>
            <input type="text" disabled class="form-control" id="id_provider" name='provider'>
          </div>
          <div class="form-group">
            <label for="id_date_joined" class="col-form-label">가입일</label>
            <input type="text" disabled class="form-control" id="id_date_joined" name='date_joined'>
          </div>
          <h4 class="sub-title">추가정보</h4>
          <div class="form-group">
            <label for="id_name" class="col-form-label">닉네임</label>
            <input type="text" disabled class="form-control" id="id_namer" name='name'>
          </div>
          <div class="form-group">
            <label for="id_sex" class="col-form-label">성별</label>
            <input type="text" disabled class="form-control" id="id_sex" name='sex'>
          </div>
          <div class="form-group">
            <label for="id_birth" class="col-form-label">생일</label>
            <input type="text" disabled class="form-control" id="id_birth" name='birth'>
          </div>
          <h4 class="sub-title">이용정보</h4>
          <div class="form-group">
            <label for="id_report" class="col-form-label">제보</label>
            <input type="text" disabled class="form-control" id="id_report" name='report'>
          </div>
          <div class="form-group">
            <label for="id_feedback" class="col-form-label">피드백</label>
            <input type="text" disabled class="form-control" id="id_feedback" name='feedback'>
          </div>
          <div class="form-group">
            <label for="id_like" class="col-form-label">관심 셀럽</label>
            <input type="text" disabled class="form-control" id="id_like" name='like'>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn" onclick="deactiveUser(this, null, null)">계정 차단</button>
        <button type="button" class="btn" data-dismiss="modal">임시 비밀번호 발급</button>
        <button type="button" class="btn" data-dismiss="modal">저장</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

apps/users/templates/user/login.html
{% extends 'index.html' %}

{% block main %}
<div class="login-main">
  <div class="container col-md-4 col-md-offset-4">
    <h4><span>C</span>.LAB 로그인</h4>
    <form method="POST">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group">
          <label>{{ field.label }}</label>
          {{ field }}
        </div>
      {% endfor %}
      <button type="submit" class="btn">로그인</button>
    </form>
    {% if form.errors %}
      {% for key, value in form.errors.items %}
        <span class="error">{{ value }}</span>
      {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock %}

apps/users/templates/user/manager_create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
{{ formset.media.css }}
{% endblock %}

{% block javascript %}
{{ formset.media.js }}
{% endblock %}

{% block content %}
<div class="container main user">
    <h4 class="sub-title">매니저 추가</h4>
    <hr />
    <div class="container">
        <form class="user-form" method="POST">
            {% csrf_token %}
            {{ formset.management_form }}
            {% for field in formset.0 %}
                {% if field.name == 'id' or field.name == 'user' %}
                    {{ field }}
                {% else %}
                    <div class="form-group row">
                        <label for="{{ field.id }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                        <div class="col-sm-10">
                            {{ field }}
                        </div>
                        <div class="col-sm-2">
                            {{ field.errors }}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
            {% for field in form %}
                <div class="form-group row">
                    <label for="{{ field.id }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field }}
                    </div>
                    <div class="col-sm-2">
                        {{ field.errors }}
                    </div>
                </div>
            {% endfor %}
            <div>
                <button type="button" class="btn" onclick="window.location.href='{% url 'user:manager'%}'">취소</button>
                <button type="submit" class="btn">저장</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

apps/users/templates/user/manager_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container main user">
    <h2 class="title">소속사 매니저</h2>
    <h4 class="sub-title">
        <a href="{% url 'user:fan' %}">팬 계정</a>
    </h4>
    <div class="search-area">
        <input type="search" placeholder="검색어를 입력하세요" name='search' />
    </div>
    <div class="user-list">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">NO</th>
                    <th scope="col">권한</th>
                    <th scope="col">아이디</th>
                    <th scope="col">이메일</th>
                    <th scope="col">소속사</th>
                    <th scope="col">관리자명</th>
                    <th scope="col">직책</th>
                    <th scope="col">연락처</th>
                    <th scope="col">담당 셀럽</th>
                    <th scope="col">가입 승인</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <td>{{ object.pk }}</td>
                    <td>
                      {% if object.manager_user.manager_type == 'n' %}
                        일반
                      {% elif object.manager_user.manager_type == 's' %}
                        관리자
                      {% else %}
                        -
                      {% endif %}
                    </td>
                    <td>{{ object.username }}</td>
                    <td>{{ object.email }}</td>
                    <td>{{ object.manager_user.entertainment }}</td>
                    <td>
                      {{ object.name }}
                    </td>
                    <td>
                      {% if object.manager_user.position %}
                        {{ object.manager_user.position }}
                      {% else %}
                        -
                      {% endif %}
                    </td>
                    <td>
                      {{ object.phone }}
                    </td>
                    <td>
                      {% for celebrity in object.manager_user.celebrity.all %}
                        {{ celebrity }}{% if not forloop.last %},{% endif %}
                      {% endfor %}
                    </td>
                    <td>
                      <a>승인</a>
                      <a>거절</a>
                    </td>
                </tr>
                {% empty %}
                    <tr>
                        <td colspan="10">등록된 소속사 매니저가 없습니다.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="">
        <button class="btn" onclick="window.location.href='{% url 'user:manager_create' %}'">소속사 관리자 추가</button>
    </div>
</div>
{% endblock %}