api/feedbacks/urls.py
from django.urls import path

from .views import FeedbackAPIView, ReportAPIView, ReportImageAPIView

app_name = 'feedback'
urlpatterns = [
    path('feedback', FeedbackAPIView.as_view()),
    path('report', ReportAPIView.as_view()),
    path('report/image', ReportImageAPIView.as_view()),
]

api/urls.py
from django.urls import path, include

app_name = 'api'
urlpatterns = [
    path('users/', include('api.users.urls', namespace='user')),
    path('schedules/', include('api.schedules.urls', namespace='schedule')),
    path('celebrities/', include('api.celebritys.urls', namespace='celebrity')),
    path('devices/', include('api.devices.urls', namespace='device')),
    path('feedbacks/', include('api.feedbacks.urls', namespace='feedback')),
    path('notifications/', include('api.notifications.urls', namespace='notification')),
]

apps/feedbacks/urls.py
from django.urls import path

from .views import ReportListView, ReportConfirmUpdateView

app_name = 'feedback'
urlpatterns = [
    path('', ReportListView.as_view(), name='list'),
    path('<pk>/update', ReportConfirmUpdateView.as_view(), name='update'),
]

apps/schedules/urls.py
from django.urls import path

from .views import ScheduleMonthlyView, ScheduleCreateView, ScheduleDetailView, ScheduleDeleteView

app_name = 'schedule'
urlpatterns = [
    path('month', ScheduleMonthlyView.as_view(), name='month'),
    path('create', ScheduleCreateView.as_view(), name='create'),
    path('<int:pk>', ScheduleDetailView.as_view(), name='detail'),
    path('<int:pk>/delete', ScheduleDeleteView.as_view(), name='delete'),
]

apps/feedbacks/models.py
from django.db import models
from django.conf import settings


class Feedback(models.Model):
    CATEGORY = (
        ('cs001', '불편사항 신고'),
        ('cs002', '서비스 개선 제안'),
        ('cs003', '서비스 문의'),
        ('cs004', '저작권/권리 침해'),
        ('cs005', '기타'),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="유저"
    )
    category = models.CharField(
        max_length=5,
        choices=CATEGORY,
        blank=True,
        verbose_name="카테고리"
    )
    content = models.TextField(
        blank=True,
        verbose_name="의견 내용"
    )
    timestamp = models.DateTimeField(
        auto_now=True,
        verbose_name="신청 날짜"
    )
    is_confirm = models.BooleanField(
        default=False,
        verbose_name="확인 여부"
    )

    class Meta:
        db_table = 'feedback'
        verbose_name = '피드백'
        verbose_name_plural = '피드백들'


class Report(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="유저"
    )
    celebrity = models.CharField(
        max_length=255,
        blank=True,
        verbose_name="제보할 연예인"
    )
    url = models.CharField(
        max_length=500,
        blank=True,
        verbose_name="제보 관련 url"
    )
    timestamp = models.DateTimeField(
        auto_now=True,
        verbose_name="신청 날짜"
    )
    is_confirm = models.BooleanField(
        default=False,
        verbose_name="확인 여부"
    )

    class Meta:
        db_table = 'report'
        verbose_name = "제보"
        verbose_name_plural = "제보들"


def report_image(instance, filename):
    return "report/%s/%s" % (
        instance.id,
        filename
    )


class ReportImage(models.Model):
    report = models.ForeignKey(
        Report,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='제보'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='시간'
    )
    image_url = models.ImageField(
        upload_to=report_image,
        verbose_name='제보'
    )

    class Meta:
        db_table = 'report_image'
        verbose_name = '제보 이미지'
        verbose_name_plural = '제보 이미지들'

    def get_report_image(self):
        return str(self.image_url.url)

api/feedbacks/views.py
from rest_framework.generics import CreateAPIView
from rest_framework.parsers import FormParser, MultiPartParser

from .serializers import FeedbackSerializer, ReportSerializer, ReportImageSerializer


class FeedbackAPIView(CreateAPIView):
    serializer_class = FeedbackSerializer


class ReportAPIView(CreateAPIView):
    serializer_class = ReportSerializer


class ReportImageAPIView(CreateAPIView):
    serializer_class = ReportImageSerializer
    parser_classes = parser_classes = (MultiPartParser, FormParser)

apps/feedbacks/views.py
from django.views.generic import ListView, UpdateView
from django.urls import reverse_lazy

from .models import Report


class ReportListView(ListView):
    # 제보 리스트 뷰
    template_name = 'feedbacks/list.html'
    queryset = Report.objects.all().order_by('-timestamp')
    paginate_by = 10


class ReportConfirmUpdateView(UpdateView):
    model = Report
    fields = [
        'is_confirm'
    ]
    success_url = reverse_lazy('feedback:list')

apps/feedbacks/templates/feedbacks/list.html
{% extends 'base.html' %}

{% block content %}
<div class="container main feedback">
  <h2 class="title">팬 제보 관리</h2>
  <div class="title-button-group" style="display:flex;justify-content: space-between;margin-bottom: 20px;">
    <button type="button" class="btn btn-outline-secondary" onclick="window.location.href='{% url 'celebrity:create' %}'">셀럽 추가</button>
    <div>
      <form method="GET" class="search-form">
        <input placeholder="검색어를 입력하세요" name="search" />
      </form>
    </div>
  </div>
  <div class="feedback-list">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">NO</th>
          <th scope="col">상태</th>
          <th scope="col">셀럽명</th>
          <th scope="col">관련자료</th>
          <th scope="col">등록일</th>
          <th scope="col">사용자명</th>
          <th scope="col">검토 여부</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
          <tr>
            <td>{{ object.pk }}</td>
            {% if object.is_confirm %}
              <td>검토완료</td>
            {% else %}
              <td>미검토</td>
            {% endif %}
            <td>{{ object.celebrity }}</td>
            <td>{{ object.url }}</td>
            <td>{{ object.timestamp }}</td>
            <td>
              {% if object.user.name %}
                {{ object.user.name }}
              {% else %}
                {{ object.user.email }}
              {% endif %}
            </td>
            <td>
              {% if not object.is_confirm %}
                <form method="POST" action="{% url 'feedback:update' object.pk %}">
                  {% csrf_token %}
                  <input type="hidden" name="is_confirm" value="true" />
                  <button type="submit">확인</button>
                </form>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}