api/schedules/urls.py
from django.urls import path

from .views import ScheduleListAPIView

app_name = 'schedule'
urlpatterns = [
    path('', ScheduleListAPIView.as_view(), name='list'),
]

api/urls.py
from django.urls import path, include

app_name = 'api'
urlpatterns = [
    path('users/', include('api.users.urls', namespace='user')),
    path('schedules/', include('api.schedules.urls', namespace='schedule')),
    path('celebrities/', include('api.celebritys.urls', namespace='celebrity')),
    path('devices/', include('api.devices.urls', namespace='device')),
    path('feedbacks/', include('api.feedbacks.urls', namespace='feedback')),
    path('notifications/', include('api.notifications.urls', namespace='notification')),
]

apps/schedules/urls.py
from django.urls import path

from .views import ScheduleMonthlyView, ScheduleCreateView, ScheduleDetailView, ScheduleDeleteView

app_name = 'schedule'
urlpatterns = [
    path('month', ScheduleMonthlyView.as_view(), name='month'),
    path('create', ScheduleCreateView.as_view(), name='create'),
    path('<int:pk>', ScheduleDetailView.as_view(), name='detail'),
    path('<int:pk>/delete', ScheduleDeleteView.as_view(), name='delete'),
]

apps/schedules/models.py
from django.db import models
from django.urls import reverse_lazy
from apps.celebritys.models import Celebrity


class Schedule(models.Model):
    title = models.CharField(
        max_length=150,
        verbose_name='스케줄명'
    )
    schedule = models.DateTimeField(
        verbose_name='일정'
    )
    celebrity = models.ManyToManyField(
        Celebrity,
        verbose_name='출연 셀럽'
    )
    url = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        verbose_name='콘텐츠 URL'
    )

    class Meta:
        db_table = 'schedule'
        verbose_name = '스케줄'
        verbose_name_plural = '스케줄들'

    def __str__(self):
        return self.title

    def get_celebrity(self):
        return [celebrity.name for celebrity in self.celebrity.all()]

    @property
    def get_absolute_url(self):
        return reverse_lazy('schedule:detail', kwargs={'pk': self.pk})

    @property
    def get_delete_url(self):
        return reverse_lazy('schedule:delete', kwargs={'pk': self.pk})


class ScheduleCategory(models.Model):
    SCHEDULE_RADIO = 'r'
    SCHEDULE_TV = 't'
    SCHEDULE_CONSERT = 'c'
    SCHEDULE_ALBUM = 'a'
    SCHEDULE_PHOTO = 'p'
    SCHEDULE_FAN = 'f'
    SCHEDULE_ETC = 'e'
    SCHEDULE_TYPE = (
        (SCHEDULE_RADIO, '라디오 스케줄'),
        (SCHEDULE_TV, '티비 스케줄'),
        (SCHEDULE_CONSERT, '공연행사'),
        (SCHEDULE_ALBUM, '앨범발매'),
        (SCHEDULE_PHOTO, '촬영'),
        (SCHEDULE_FAN, '팬미팅'),
        (SCHEDULE_ETC, '기타'),
    )

    schedule = models.ForeignKey(
        Schedule,
        on_delete=models.CASCADE,
        verbose_name='스케줄'
    )
    first_category = models.CharField(
        max_length=5,
        choices=SCHEDULE_TYPE,
        default=SCHEDULE_TV,
        verbose_name='상위 카테고리'
    )
    second_category = models.CharField(
        max_length=5,
        null=True,
        blank=True,
        verbose_name='하위 카테고리'
    )
    content = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        verbose_name='부가정보'
    )

    class Meta:
        db_table = 'schedule_category'
        verbose_name = '스케줄 카테고리'
        verbose_name_plural = '스케줄 카테고리들'

    def __str__(self):
        return self.first_category

apps/schedules/forms.py
from django import forms
from django_select2 import forms as select2_forms

from .models import Schedule
from apps.celebritys.models import Celebrity


class ScheduleForm(forms.ModelForm):
    # 스케줄 폼
    celebrity = forms.ModelMultipleChoiceField(
        label="담당 셀럽",
        queryset=Celebrity.objects.all(),
        widget=select2_forms.Select2MultipleWidget,
        required=False,
    )

    class Meta:
        model = Schedule
        fields = (
            'schedule',
            'title',
            'celebrity',
            'url',
        )

api/schedules/views.py
from datetime import date, datetime, timedelta
from rest_framework.generics import ListAPIView

from apps.schedules.models import Schedule
from apps.celebritys.models import Celebrity

from .serializers import ScheduleSerializer


class ScheduleListAPIView(ListAPIView):
    # 스케줄 목록 API
    queryset = Schedule.objects.all()
    serializer_class = ScheduleSerializer

    def get_queryset(self):
        queryset = super().get_queryset()
        user_like_celubs = self.request.user.celebrity_set.all()
        queryset = queryset.filter(celebrity__in=user_like_celubs)

        celeb = self.request.GET.getlist('celeb', None)
        date_type = self.request.GET.get('date_type', None)
        req_date = self.request.GET.get('date', None)

        if celeb:
            selected_celubs = Celebrity.objects.filter(id__in=celeb)
            queryset = queryset.filter(celebrity__in=selected_celubs)

        if not date_type and not req_date:
            # filter by today
            queryset = queryset.filter(
                schedule__lte=date.today() + timedelta(days=30)
            ).order_by('schedule')
        elif date_type:
            if date_type == 'yesterday':
                queryset = queryset.filter(
                    schedule__date=date.today() - timedelta(days=1))
            elif date_type == 'tomorrow':
                queryset = queryset.filter(
                    schedule__date=date.today() + timedelta(days=1))
            elif date_type == 'week':
                queryset = queryset.filter(
                    schedule__week=date.today().isocalendar()[1]).order_by('schedule')
        elif req_date:
            queryset = queryset.filter(
                schedule__date=datetime.strptime(req_date, "%Y-%m-%d").date())
        else:
            queryset = queryset.none()

        return queryset

apps/schedules/views.py
import datetime
import calendar
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.utils.safestring import mark_safe
from django.utils import timezone
from django.urls import reverse_lazy

from .calendar import ScheduleCalendar
from .models import Schedule
from .forms import ScheduleForm


class ScheduleMonthlyView(ListView):
    template_name = 'schedule/month.html'
    queryset = Schedule.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        date = self.request.GET.get('date')
        if date:
            repay_datetime = datetime.datetime.strptime(date, '%Y-%m-%d')
            repay_datetime_aware = timezone.make_aware(repay_datetime).date()
            queryset = queryset.filter(
                schedule__year=repay_datetime_aware.year,
                schedule__month=repay_datetime_aware.month,
                schedule__day=repay_datetime_aware.day
            )
        else:
            queryset = queryset.filter(
                schedule__year=timezone.now().date().year,
                schedule__month=timezone.now().date().month,
                schedule__day=timezone.now().date().day,
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = datetime.date.today()
        date = self.request.GET.get('date')

        if date:
            date = timezone.make_aware(
                datetime.datetime.strptime(date, '%Y-%m-%d'))
            d = date
        else:
            date = timezone.now()
        cal = ScheduleCalendar(calendar.SUNDAY)
        html_calendar = cal.formatmonth(
            d.year, d.month, d, date, withyear=False)
        html_calendar = html_calendar.replace(
            '<td ', '<td ')

        context.update({
            'calendar': mark_safe(html_calendar),
            'date': date
        })
        return context


class ScheduleCreateView(CreateView):
    template_name = 'schedule/create.html'
    queryset = Schedule.objects.all()
    form_class = ScheduleForm
    success_url = reverse_lazy('schedule:month')


class ScheduleDetailView(UpdateView):
    template_name = 'schedule/update.html'
    model = Schedule
    form_class = ScheduleForm
    success_url = reverse_lazy('schedule:month')


class ScheduleDeleteView(DeleteView):
    model = Schedule
    success_url = reverse_lazy('schedule:month')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

apps/schedules/templates/schedule/create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
{{ form.media.css }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.3/jquery-ui-timepicker-addon.min.css">
{% endblock %}

{% block javascript %}
{{ form.media.js }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.3/jquery-ui-timepicker-addon.min.js"></script>
<script>
    $(function() {
        $("#id_schedule").datetimepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: "+1w",
            changeMonth: true,
            numberOfMonths: 2,
            controlType: 'select',
	        oneLine: true,
	        timeFormat: 'HH:mm',
            onClose: function( selectedDate ) {
                $( "#id_schedule" ).datepicker( "option", "minDate", selectedDate );
            }
        });
    });
</script>
{% endblock %}

{% block content %}
<div class="container main schedule">
    <h4 class="sub-title">스케줄 등록</h4>
    <hr />
    <div class="conatiner">
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group row">
                    <label for="{{ field.id }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field }}
                    </div>
                    <div class="col-sm-2">
                        {{ field.errors }}
                    </div>
                </div>
            {% endfor %}
            <div>
                <button type="button" class="btn" onclick="window.location.href='{% url 'schedule:month' %}'">취소</button>
                <button type="submit" class="btn">저장</button>
            </div>
        </form>
    </div>
    </div>
{% endblock %}

apps/schedules/templates/schedule/month.html
{% extends 'base.html' %}
{% load staticfiles tz calendar %}

{% block content %}
<div class="container main schedule">
    <h2 class="title">
        {{ date|date:"Y년 m월 d일" }}
        <img 
    </h2>
    <div class="filter">
        <div class="calendar-type">
            <a href="{% url 'schedule:month' %}">
                <img src="{% static 'img/month.svg' %}" width=20 height=20 />
                월간달력
            </a>
        </div>
        <div class="month-type">
          <a href="?date={{ date|get_prev_month }}">
              <img src="{% static 'img/month_prev.svg' %}" width=30 height=30 />
          </a>
          <a href="?date={{ date|get_next_month }}">
              <img src="{% static 'img/month_next.svg' %}" width=30 height=30 />
          </a>
          <a class="btn" href="?date={% now "Y-m-d" %}">오늘</a>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-8 calendar">
                {{ calendar }}
            </div>
            <div class="col-4">
                <div class="celebrity-list">
                    <h5>셀럽</h5>
                </div>
                <div class="schedule-list">
                    <h4>{{ date|date:"Y년 m월 d일" }}</h4>
                    <hr />
                    {% for object in object_list %}
                        <div class="schedule-item">
                            <div class="time">
                                <img src="{% static 'img/time.svg' %}" width=15 height=15 />
                                {{ object.schedule|localtime|date:"H:i" }}
                            </div>
                            <div>
                                <img src="{% static 'img/calendar.svg' %}" width=15 height=15 />
                                {{ object.title }}
                            </div>
                            <div>
                                <img src="{% static 'img/people.svg' %}" width=15 height=15 />
                                {% for celebrity in object.get_celebrity %}
                                    {{ celebrity }}{% if not forloop.last %},{% endif %}
                                {% endfor %}
                            </div>
                            <div class="">
                                <a href="{{ object.get_absolute_url }}">
                                    <img src="{% static 'img/schedule-add.svg' %}" width=15 height=15 style="cursor: pointer;"/>
                                </a>
                            </div>
                        </div>
                        {% if not forloop.last %}
                            <hr/>
                        {% endif %}
                    {% empty %}
                        <div class="no-schedule">
                            등록된 스케줄이 없습니다.
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <a href="{% url 'schedule:create' %}" class="add-schedule">
        <img src="{% static 'img/add_schedule.svg' %}" width=20 height=20 />
        스케줄 추가
    </a>
</div>
{% endblock %}

apps/schedules/templates/schedule/update.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
{{ form.media.css }}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.3/jquery-ui-timepicker-addon.min.css">
{% endblock %}

{% block javascript %}
{{ form.media.js }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-timepicker-addon/1.6.3/jquery-ui-timepicker-addon.min.js"></script>
<script>
    $(function() {
        $("#id_schedule").datetimepicker({
            dateFormat: "yy-mm-dd",
            defaultDate: "+1w",
            changeMonth: true,
            numberOfMonths: 2,
            controlType: 'select',
	        oneLine: true,
	        timeFormat: 'HH:mm',
            onClose: function( selectedDate ) {
                $( "#id_schedule" ).datepicker( "option", "minDate", selectedDate );
            }
        });
    });
</script>
{% endblock %}

{% block content %}
<div class="container main schedule">
    <h4 class="sub-title">스케줄 수정</h4>
    <hr />
    <div class="conatiner">
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group row">
                    <label for="{{ field.id }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field }}
                    </div>
                    <div class="col-sm-2">
                        {{ field.errors }}
                    </div>
                </div>
            {% endfor %}
            <div>
                <button type="button" class="btn" onclick="window.location.href='{{ object.get_delete_url }}'">삭제</button>
                <button type="button" class="btn" onclick="window.location.href='{% url 'schedule:month' %}'">취소</button>
                <button type="submit" class="btn">저장</button>
            </div>
        </form>
    </div>
    </div>
{% endblock %}