api/schedules/urls.py
from django.urls import path

from .views import ScheduleListAPIView

app_name = 'schedule'
urlpatterns = [
    path('', ScheduleListAPIView.as_view(), name='list'),
]

api/urls.py
from django.urls import path, include

app_name = 'api'
urlpatterns = [
    path('users/', include('api.users.urls', namespace='user')),
    path('schedules/', include('api.schedules.urls', namespace='schedule')),
    path('celebrities/', include('api.celebritys.urls', namespace='celebrity')),
    path('devices/', include('api.devices.urls', namespace='device')),
    path('feedbacks/', include('api.feedbacks.urls', namespace='feedback')),
    path('notifications/', include('api.notifications.urls', namespace='notification')),
]

apps/bases/urls.py
from django.urls import path

from .views import HomeView, PrivateView

app_name = 'base'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('private', PrivateView.as_view(), name='private'),
]

apps/entertainments/urls.py
from django.urls import path

from .views import (
    EntertainmentListView,
    EntertainmentCreateAPIView,
    EntertainmentAPIView,
)

app_name = 'entertainment'
urlpatterns = [
    path('<int:pk>', EntertainmentAPIView.as_view(), name='api'),
    path('list', EntertainmentListView.as_view(), name='list'),
    path('create', EntertainmentCreateAPIView.as_view(), name='create'),
]

apps/schedules/urls.py
from django.urls import path

from .views import ScheduleMonthlyView, ScheduleCreateView, ScheduleDetailView, ScheduleDeleteView

app_name = 'schedule'
urlpatterns = [
    path('month', ScheduleMonthlyView.as_view(), name='month'),
    path('create', ScheduleCreateView.as_view(), name='create'),
    path('<int:pk>', ScheduleDetailView.as_view(), name='detail'),
    path('<int:pk>/delete', ScheduleDeleteView.as_view(), name='delete'),
]

apps/users/urls.py
from django.urls import path

from .views import (
    UserFanListView,
    UserFanAPIView,
    UserManagerListView,
    UserManagerCreateView,
    UserLoginView,
    UserLogoutView,
)

app_name = 'user'
urlpatterns = [
    path('login', UserLoginView.as_view(), name='login'),
    path('logout', UserLogoutView.as_view(), name='logout'),
    path('fan', UserFanListView.as_view(), name='fan'),
    path('fan/<int:pk>', UserFanAPIView.as_view(), name='fan_detail'),
    path('manager', UserManagerListView.as_view(), name='manager'),
    path('manager/create', UserManagerCreateView.as_view(), name='manager_create'),
]

apps/bases/views.py
from django.views.generic import RedirectView, TemplateView
from django.urls import reverse_lazy


class HomeView(RedirectView):
    url = reverse_lazy('celebrity:list')


class PrivateView(TemplateView):
    template_name = 'private.html'

apps/bases/templates/base.html
{% extends 'index.html' %}

{% block main %}
{% include 'header.html' %}
<div class="container-fluid">
  {% block content %}
  {% endblock %}
</div>
{% endblock %}

apps/bases/templates/header.html
<nav class="main-header navbar navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'base:home' %}"><span>C</span>.LAB</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse container" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'schedule:month' %}">스케줄 관리</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'entertainment:list' %}">기획사 관리</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'celebrity:list' %}">셀럽 관리</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:manager' %}">사용자 관리</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'feedback:list' %}">피드백 관리</a>
            </li>
        </ul>
    </div>
    <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
        <li class="nav-item dropdown">
            <a class="nav-item nav-link dropdown-toggle mr-md-2" href="#" id="bd-versions" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if user.name %}
                    {{ user.name }}
                {% else %}
                    {{ user.email }}
                {% endif %}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="bd-versions">
                <a class="dropdown-item" href="{% url 'user:logout' %}">로그아웃</a>
            </div>
        </li>
    </ul>
</nav>

apps/bases/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <title>C.LAB - 연예인 스케줄 관리</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.structure.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.theme.min.css">
  <link rel="stylesheet" href="{% static 'app.css' %}">
  {% block css %}
  {% endblock %}

  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/4.2.2/jquery.form.min.js" integrity="sha384-FzT3vTVGXqf7wRfy8k4BiyzvbNfeYjK+frTVqZeNDFl8woCbF0CYG6g2fMEFFo/i" crossorigin="anonymous"></script>
  <script src="{% static 'app.js' %}"></script>
  {% block javascript %}
  {% endblock %}
</head>
<body>
  {% block main %}
  {% endblock %}
  {% block modal %}
  {% endblock %}
</body>

</html>

apps/bases/templates/private.html
{% extends 'index.html' %}

{% block main %}
<div class="contaienr">
    <h4>셀럽 개인정보 취급방침</h4>
    <h5>개인정보처리방침</h5>
    <p>
        비앤플라워(이하 '회사'라 함)는 정보통신망 이용촉진 및 정보보호 등에 관한 법률, 개인정보보호법, 통신비밀보호법, 전기통신사업법 등 관련 법령에 따라 정보통신서비스제공자가 준수하여야 할 개인정보보호 규정을 준수하며, 관련 법령에 의거한 개인정보처리방침을 정하여 이용자 권익 보호에 최선을 다하고 있습니다.
        본 개인정보처리방침은 회사가 운영하는 셀럽(Celuv) 서비스(이하 ‘셀럽’이라 합니다) 등 관련 제반서비스에 적용되며 다음과 같은 내용을 담고 있습니다.
        이 개인정보처리방침에서 사용하는 용어의 의미는 관련 법령 및 회사의 이용약관에서 정한 바에 따르며, 그 밖의 사항은 일반적인 상관례에 따릅니다.
    </p>
    <h5>1. 수집하는 개인정보의 항목 및 수집방법</h5>
    <p> 
        가. 수집하는 개인정보의 항목
        회사는 회원이 입력한 정보를 기반으로 회원가입, 셀럽 서비스의 제공, 원활한 고객상담 등을 위하여 다음과 같은 정보를 수집합니다.
        1) 필수 항목
        ● 회원의 아이디(이메일), 비밀번호
        ● 회원의 이름, 휴대폰번호•이메일 등 연락처, 관계정보 등 정보
        ● OS 버전, 단말기 정보 등 운영체제 및 하드웨어 환경정보
        2) 선택 항목
        ● 프로필 사진, 닉네임, 성별, 생일 등 정보
        ● 외부 서비스 계정과 연동할 경우, 외부 서비스에서 제공받는 계정 정보, 서비스 이용 정보 및 기타 회원이 제공에 동의한 개인 정보
        3) 서비스 이용시 아래와 같은 정보들이 자동으로 생성되어 수집될 수 있습니다.
        ● IP Address, 쿠키, 기기정보, 방문 일시, 서비스 이용 기록, 불량 이용 기록 등
        4) 유료 서비스 이용 과정에서 결제 등을 위하여 불가피하게 필요한 때에는 다음의 정보가 수집될 수 있습니다.
        ● 신용카드 정보, 휴대폰번호, 통신사 정보 등과 같이 결제에 필요한 정보
        나. 개인정보의 수집방법
        회사는 다음과 같은 방법으로 개인정보를 수집합니다.
        1) 서비스 가입이나 사용 중 이용자의 자발적 제공을 통한 수집
        2) 회원의 선택에 따라 네이버, 페이스북, 구글 등의 아이디를 이용하여 로그인하는 회원의 경우 해당 회사에서 회원에게 동의를 받은 후 제공받아 수집
        3) 그 외 제휴된 외부 기업이나 단체로부터 제공
        4) 기기정보, 서비스 이용 기록 등 생성정보는 서비스 이용과정에서 자동으로 수집
    </p>
    <h5>2. 개인정보의 수집 및 이용 목적</h5>
    <p>
        회사는 다음과 같은 목적으로 이용자 등의 개인정보를 수집합니다.
        가. 회원관리
        회원제 서비스 이용에 따른 본인확인, 회원 식별을 위한 목적, 가입의사 확인, 가입 및 가입횟수 제한, 원활한 의사소통 경로의 확보, 고객 문의에 대한 응답, 새로운 정보의 소개 및 고지사항 전달, 불량회원의 부정이용방지와 비인가 사용방지, 본인확인 및 분쟁 조정을 위한 기록보존, 불만 등 민원처리 등
        나. 셀럽 서비스 기능의 제공
        회원의 셀러브리티 즐겨찾기ᆞ알림, 스케줄 정보 제보를 위한 메시지의 송ᆞ수신 또는 게시물의 작성ᆞ게재ᆞ조회 등 서비스 내에서 회원의 계정을 통하여 이용할 수 있는 서비스 등을 제공
        다. 서비스 제공에 관한 계약 이행 및 필요 시 유료 서비스 제공에 따른 요금정산
        약관 개정 등 고지사항 전달, 유료 서비스 제공에 구매 및 요금 결제, 상품 및 서비스 배송 등
        라. 서비스 개선 및 신규 서비스 개발
        인구 통계학적 분석, 서비스 방문 및 이용 기록의 분석, 인맥 및 관심사 등에 기반한 맞춤형 서비스 제공, 개인정보 및 관심에 기반한 회원간 관계의 형성 등 신규 서비스 요소를 발굴하고 기존 서비스의 개선에 이용
        마. 마케팅 및 광고성 정보의 제공
        새로운 기능 출시 안내, 이용 방법 및 이용 혜택 안내, 각종 이벤트 참여 기회 및 광고성 정보 게재ᆞ제공, 광고 반응 내역에 대한 통계 자료의 외부 제공 등 법령 등의 이행 및 준수 법령 등에 규정된 의무의 이행, 법령이나 이용약관에 반하여 이용자에게 피해를 줄 수 있는 잘못된 이용행위의 방지 등
    </p>
    <h5>3. 개인정보의 제3자 제공 및 처리위탁</h5>
    <p>
        회사는 회원의 개인정보를 '개인정보의 수집 및 이용 목적'에서 명시한 범위에서 사용하며, 이에 따라 서비스 이용과정에서 다음의 정보가 공개될 수 있습니다. 또한, 서비스의 목적상 필수적으로 제공되어야 하거나 회원의 사전 동의가 있는 경우 또는 아래 예외적인 경우를 제외하고는, 그 범위를 초과하여 이용하거나 제3자에 제공하지 않습니다.
        가. 개인정보의 공개
        셀럽 서비스 이용 도중 회원의 정보 및 회원이 선택적으로 입력한 기타 정보를 공유시 연결된 외부 서비스에 공개될 수 있습니다. 
        나. 회원이 제공에 동의한 정보
        외부 제휴된 기업 또는 단체의 서비스를 이용하기 위하여 개인정보 제공에 동의한 경우 법령에 특별한 규정이 있는 경우 수사기관이 수사 목적으로 정해진 절차와 방법에 따라 요구한 경우
        다. 개인정보의 위탁제공
        회사는 서비스의 향상을 위하여 아래와 같이 개인정보를 위탁하고 있으며, 관련 법령에 따라 위탁계약시 개인정보가 안전하게 관리될 수 있도록 필요한 사항을 규정하고 있습니다. 회사는 수탁자가 변경되는 경우 지체없이 본 개인정보 처리방침을 통하여 공개합니다.
        
            Amazon Web Service
        수탁업체명
        Amazon Web Service
        위탁업무 및 목적
        데이터 보관 및 시스템 운영
        개인정보 이전국가
        대한민국(AWS Seoul Region)
        이전되는 개인정보 항목
        서비스 제공 과정에서 수집한 모든 개인정보
        개인정보 이전일시
        회원가입 시점
        개인정보 이전방법
        AWS 클라우드 컴퓨팅 환경에 개인정보 보관
        개인정보 보유, 이용기간
        회원탈퇴 또는 개인정보 유효기간 도래시까지 보관
    </p>
    <h5>4. 개인정보 보유 및 이용기간</h5>
    <p>회원의 개인정보는 원칙적으로 개인정보의 수집 및 이용 목적이 달성되면 지체 없이 파기합니다. 단, 다음의 정보에 대해서는 아래의 이유로 명시한 기간 동안 보관합니다.
            가. 회사 내부 방침에 의한 정보보유
            부정이용기록 보유 : 1년 (부정 이용 방지)
            
            나. 관련 법령에 의한 정보보유
            상법, 전자상거래 등에서의 소비자보호에 관한 법률 등 관련법령의 규정에 의하여 일정기간 정보를 보유하여야 할 필요가 있을 경우 회사는 보관하는 정보를 일정기간 보유하며, 보유기간은 아래와 같습니다.
            ● 계약 또는 청약철회 등에 관한 기록 보유 : 5년 (전자상거래 등에서의 소비자보호에 관한 법률)
            ● 대금결제 및 재화 등의 공급에 관한 기록 보유 : 5년 (전자상거래 등에서의 소비자보호에 관한 법률)
            ● 소비자 불만 또는 분쟁처리에 관한 기록 보유 : 3년 (전자상거래 등에서의 소비자보호에 관한 법률)
            ● 본인확인에 관한 기록 보유 : 6개월 (정보통신망 이용촉진 및 정보보호 등에 관한 법률)
            ● 방문에 관한 기록 보유 : 3개월 (통신비밀보호법)</p>
    <h5>5. 개인정보의 열람, 수정, 삭제 및 개인정보의 도용</h5>
    <p>회원은 언제든지 자신의 개인정보를 열람, 공개 및 비공개 처리하거나 수정할 수 있으며, 삭제 및 파기를 요청할 수 있습니다.
            가. 개인정보의 열람 및 수정 요청
            회원 및 법정대리인은 언제든지 등록되어 있는 본인 또는 만 14세미만 아동의 개인정보를 조회, 수정할 수 있습니다. 회원 또는 법정대리인은 당해 개인정보의 조회, 수정을 위하여 셀럽 서비스에 등록된 정보를 클릭하거나, 설정 메뉴를 클릭하여 계정 등 등록된 개인정보를 직접 열람하거나 수정할 수 있습니다.
            나. 개인정보의 삭제(회원탈퇴)
            회원 및 만 14세 미만 아동의 법정대리인이 회원탈퇴를 원하는 경우, 모바일 애플리케이션 또는 웹사이트로 로그인한 후 ‘메뉴-내 계정 정보-회원 탈퇴'를 통해 직접 탈퇴할 수 있습니다. 만일, 직접 탈퇴가 어려운 경우 개인정보관리담당자에게 서면, 전화 또는 이메일로 연락하시면 지체없이 조치를 취하겠습니다.
            다. 개인정보의 도용
            회사는 타인의 휴대폰 번호, 이메일 주소, 페이스북 등 제휴업체 아이디 또는 기타 개인정보를 도용하여 회원가입한 자 또는 셀럽을 이용한 자를 발견한 경우 지체 없이 해당 아이디에 대한 서비스 이용 정지 또는 회원 탈퇴 등 필요한 조치를 취합니다.
            </p>
    <h5>6. 개인정보의 파기</h5>
    <p>회원의 개인정보는 원칙적으로 개인정보의 수집 및 이용 목적이 달성되면 지체 없이 파기합니다. 회사의 개인정보 파기절차 및 방법은 다음과 같습니다.
            가. 파기절차
            회원이 서비스 가입 등을 위해 입력한 정보는 목적이 달성된 후 별도의 DB 또는 보관 장소로 옮겨져 내부 방침 및 기타 관련 법령에 의한 정보보호 사유에 따라(개인정보 보유 및 이용기간 참조) 일정 기간 저장된 후 파기됩니다. 위 별도 보관된 개인정보는 정해진 목적 이외의 다른 목적으로 이용되지 않습니다.
            다. 파기방법
            종이에 출력된 개인정보는 분쇄기로 분쇄하거나 소각을 통하여 파기합니다. 전자적 파일 형태로 저장된 개인정보는 기록을 재생할 수 없는 기술적 방법을 사용하여 삭제합니다.
            </p> 
            
            
    <h5>7. 쿠키의 운영</h5>
    <p>쿠키란 셀럽 서비스 접속시 이용자의 저장장치에 전송하는 특별한 텍스트 파일(text file)을 말합니다. 쿠키는 웹사이트의 서버(server)에서만 읽어들일 수 있는 형태로 전송되며 개인이 사용하는 브라우저(browser)의 디렉터리(directory) 하위에 저장됩니다. 모바일 애플리케이션과 같이 쿠키 기술을 사용할 수 없는 경우에는 쿠키와 유사한 기능을 수행하는 기술(광고식별자 등)을 사용할 수도 있습니다.
            가. 쿠키의 사용 목적
            셀럽이 쿠키를 통해 수집하는 정보는 '수집하는 개인정보 항목'과 같으며 '개인정보의 수집 및 이용목적' 외의 용도로는 이용되지 않습니다.
            
            나. 쿠키 설정 거부
            이용자는 쿠키에 대한 선택권을 가지고 있습니다. 웹 브라우저 옵션(option)을 선택함으로써 모든 쿠키의 허용, 동의를 통한 쿠키의 허용, 모든 쿠키의 차단을 스스로 결정할 수 있습니다. 단, 쿠키 저장을 거부할 경우에는 로그인이 필요한 일부 서비스를 이용하지 못할 수도 있습니다.</p>
    <h5>8. 회원의 권리와 의무</h5>
    <p> 회원은 개인정보를 보호받을 권리와 함께 스스로를 보호하고 타인의 정보를 침해하지 않을 의무도 가지고 있습니다. 비밀번호를 포함한 회원의 개인정보가 유출되지 않도록 조심하시고 게시물을 포함한 타인의 개인정보를 훼손하지 않도록 유의해 주십시오.
            회원이 입력한 부정확한 정보로 인해 발생하는 사고의 책임은 이용자 자신에게 있습니다. 회원은 개인정보를 최신의 상태로 정확하게 입력하여 불의의 사고를 예방하여야 할 의무가 있습니다.
            회원이 위 책임을 다하지 못하고 타인의 정보 및 존엄성을 훼손할 시에는 『정보통신망 이용촉진 및 정보보호 등에 관한 법률』등 관련 법률에 의해 처벌받을 수 있습니다.</p>
    <h5>9. 개인정보의 기술적/관리적 보호대책</h5>
    <p>회사는 회원의 개인정보를 처리함에 있어 개인정보가 분실, 도난, 유출, 변조 또는 훼손되지 않도록 안전성 확보를 위하여 다음과 같은 기술적/관리적 대책을 강구하고 있습니다.
            가. 해킹 등에 대비한 대책
            회사는 해킹이나 컴퓨터 바이러스 등에 의해 회원의 개인정보가 유출되거나 훼손되는 것을 막기 위해 최선을 다하고 있습니다. 회원의 개인정보나 자료가 유출되거나 손상되지 않도록 방지하고 있으며, 암호화 통신 등을 통하여 네트워크상에서 개인정보를 안전하게 전송할 수 있도록 하고 있습니다. 그리고 침입차단시스템을 이용하여 외부로부터의 무단 접근을 통제하고 있습니다.
            나. 처리 직원의 최소화 및 교육
            회사의 개인정보관련 처리 직원은 담당자에 한정시키고 있고 이를 위한 별도의 비밀번호를 부여하여 정기적으로 갱신하고 있으며, 담당자에 대한 수시 교육을 통하여 회사의 개인정보처리방침의 준수를 항상 강조하고 있습니다.
            다. 개인정보보호전담기구의 운영
            회사는 사내 개인정보보호전담기구 등을 통하여 회사의 개인정보처리방침의 이행사항 및 담당자의 준수여부를 확인하여 문제가 발견될 경우 즉시 수정하고 바로 잡을 수 있도록 노력하고 있습니다. 단, 회원 본인의 부주의나 회사의 고의 또는 중대한 과실이 아닌 사유로 개인정보가 유출되어 발생한 문제에 대해 회사는 일체의 책임을 지지 않습니다.
            </p>
    <h5>10. 개인정보보호책임자 및 담당자의 연락처</h5>
    <p>귀하께서는 회사의 서비스를 이용하시며 발생하는 모든 개인정보보호 관련 민원을 개인정보보호책임자 혹은 담당부서로 신고하실 수 있습니다. 회사는 회원의 신고사항에 대하여 신속하게 답변을 드릴 것입니다.
            개인정보보호책임자
            이 름 : 송선욱
            소 속 : 비앤플라워
            직 위 : 대표
            전 화 : 010-3757-1167
            이메일 : entresong@gmail.com
            개인정보관리담당자
            이 름 : 송선욱
            소 속 : 비앤플라워
            직 위 : 대표
            전 화 : 010-3757-1167
            이메일 : entresong@gmail.com
            기타 개인정보침해에 대한 신고나 상담이 필요하신 경우에는 아래 기관에 문의하시기 바랍니다.
            ● 개인정보침해신고센터 (www.118.or.kr / 118)
            ● 정보보호마크인증위원회 (www.eprivacy.or.kr / 02-580-0533~4)
            ● 대검찰청 첨단범죄수사과 (www.spo.go.kr / 02-3480-2000)
            ● 경찰청 사이버테러대응센터 (www.ctrc.go.kr / 02-392-0330)</p>
            
            <h5>11. 기타</h5>
            <p>셀럽 서비스 내에 링크되어 있는 웹사이트 등 타 서비스들이 개인정보를 수집하는 행위에 대해서는 본 셀럽 개인정보처리방침이 적용되지 않음을 알려드립니다.</p>
            <h5>12. 고지의 의무</h5>
            <p>        
                    현 개인정보처리방침 내용 추가, 삭제 및 수정이 있을 시에는 시행일 최소 7일전부터 서비스 내 '공지사항'을 통해 공지할 것입니다. 다만, 이용자 권리의 중대한 변경이 발생할 때에는 최소 30일 전에 공지하도록 하며 필요 시 이용자의 동의를 다시 받을 수도 있습니다.
                    공고일자 : 2017. 10. 16.
                    시행일자 : 2017. 10. 20.</p>
            
            
            
            
            
            
            
            
            
            
            
           
            
            
            
            
            
            
            
            
    
</div>
{% endblock %}